# Generated by Django 4.0.6 on 2022-07-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0037_auto_20190614_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forfait',
            old_name='heur_payer',
            new_name='heures_payées',
        ),
        migrations.RenameField(
            model_name='forfait',
            old_name='total_heur',
            new_name='total_heures',
        ),
    ]
